name: Build Boorusama APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglu1-mesa

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.3

      - name: Get Flutter packages
        run: flutter pub get

      - name: Run gen.sh script to generate boilerplate
        run: chmod +x ./gen.sh && ./gen.sh

      - name: Build release APK
        run: flutter build apk --release --flavor prod

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: boorusama-prod-apk
          path: build/app/outputs/flutter-apk/app-prod-release.apk
